name: revchek
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.PNG"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.PNG"

flutter:
  uses-material-design: true

  # assets:
  #   - assets/
